Update webcam and docs
mainsail-crew/docs pull request #14
Opened 2022-03-04 12:17 UTC by prcutler

Add webcam paragraph for Mainsail 2.1.  Review and update top-level docs pages for grammar and readability.

2022-03-07 07:52 UTC, lixxbox requested changes
quicktips/multi-cam.md changed to features/webcam.md some time ago.
this PR would add quicktips/multi-cam.md again.

could you please edit your PR and add your changes to the new file?

2022-03-09 09:11 UTC, lixxbox commented
moved here: https://github.com/mainsail-crew/docs/pull/14

2022-03-09 09:27 UTC, lixxbox commented
fail on my side 😅

2026-02-15 17:12 UTC, mryel00 commented
Hey, thank you for your PR and sry that it took so long to respond further.
We moved to GitBook a while back and now we move back here.
Therefore we rewrite and update these docs based on the GitBook docs right now and cannot merge your PR.
I hope you will contribute in the future again, we would highly appreciate it :smile:

2026-02-15 17:12 UTC, closed without merging