docs: add docker guide, and improve index
mainsail-crew/docs pull request #16
Opened 2022-03-09 21:08 UTC by pataar

This adds a guide for installing Mainsail through Docker, and improves the `index.md` just like the `README.md` from the repository.﻿

2022-03-12 06:00 UTC, lixxbox approved these changes
LGTM

2022-03-12 12:49 UTC, prcutler requested changes
Hi, 

This looks great! Two tiny things in docker.md that I'd recommend:

Line 11: nginx should be lower case
Line 21: Remove the word "easily"  - if they're reading the docs, they might not be finding it easy at that moment in time.

That's it - this is excellent!

2022-03-12 13:12 UTC, lixxbox commented
I would stick with "NGINX". That's how it's spelled on their website https://www.nginx.com and that's how i included it in the spell checker and changed it in the rest of the docs.

2022-03-13 22:39 UTC, lixxbox requested changes

2022-03-13 22:39 UTC, lixxbox commented on index.md
> +- **[Theming Support](/features/theming/):** _Customizable user interface including logos, backgrounds, and custom CSS_
Link should point to „/features/theming“ without „/„ at the end.

2022-03-14 13:45 UTC, pataar commented
@lixxbox @prcutler Feedback fixed!

2022-03-14 18:53 UTC, lixxbox approved these changes

2022-03-14 18:53 UTC, merged