docs: rework the development docs
mainsail-crew/docs pull request #8
Opened 2022-02-27 22:53 UTC by th33xitus

* remove outdated Docker page
* rename Standalone page to Environment
* rework instructions to set up a development environment

Signed-off-by: Dominik Willner <th33xitus@gmail.com>

2022-02-27 23:32 UTC, meteyou approved these changes

2022-02-28 07:38 UTC, lixxbox commented on development/environment.md
> +Now edit the `.env.development.local` file to reflect your printers network configuration. \
to correct the line break, remove the following blank line

2022-02-28 07:39 UTC, lixxbox commented on development/environment.md
> +Run the follwing command to install all required modules and dependencies:
`follwing` typo

2022-02-28 07:41 UTC, lixxbox requested changes
i have commented on some passages. apart from that, it looks good to me.

2022-02-28 07:54 UTC, lixxbox approved these changes
LGTM 👍

2022-02-28 07:55 UTC, merged